### ISSUE TITLE
Error in workflow ...

### ISSUE THREAD

**Issue by alexreg** [danielecook/gist-alfred#8]
When I type `gg`:

`'NoneType' object is not interable`

Mind releasing a fix for this? It may because I had to run Fixum to get it working for Alfred 3.

**Comment by danielecook** [comment]
What does the debug output say in alfred?

**Comment by alexreg** [comment]
```
Starting debug for 'gist'

[2017-11-21 21:41:27][ERROR: input.scriptfilter] Code 1: 21:41:26 workflow.py:1884 DEBUG    loading cached data: /Users/alex/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.danielecook.gist/__workflow_update_status.cpickle
21:41:26 workflow.py:2462 DEBUG    update_data: {u'available': False}
21:41:26 workflow.py:2249 DEBUG    workflow version: 0.4.0
21:41:26 workflow.py:1657 DEBUG    reading settings from /Users/alex/Library/Application Support/Alfred 3/Workflow Data/com.danielecook.gist/settings.json
21:41:26 workflow.py:2532 DEBUG    Update check not due
21:41:26 workflow.py:1760 DEBUG    no data stored for `gists`
21:41:26 background.py:188 DEBUG    [update] command cached: /Users/alex/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.danielecook.gist/update.argcache
21:41:26 background.py:192 DEBUG    [update] passing job to background runner: [u'/usr/bin/python', '/Users/alex/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A3065E7E-5BBB-4480-8321-AD28AE046961/workflow/background.pyc', 'update']
21:41:27 background.py:197 DEBUG    [update] background job started
21:41:27 workflow.py:1760 DEBUG    no data stored for `gists`
21:41:27 workflow.py:1760 DEBUG    no data stored for `n_starred`
21:41:27 workflow.py:1760 DEBUG    no data stored for `n_forked`
21:41:27 workflow.py:1760 DEBUG    no data stored for `n_public`
21:41:27 workflow.py:1760 DEBUG    no data stored for `n_private`
21:41:27 workflow.py:2267 ERROR    'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.A3065E7E-5BBB-4480-8321-AD28AE046961/workflow/workflow.py", line 2260, in run
    func(self)
  File "gist.py", line 45, in main
    for gist in gists:
TypeError: 'NoneType' object is not iterable
21:41:27 workflow.py:2290 DEBUG    workflow finished in 0.080 seconds
```

**Comment by danielecook** [comment]
Did you do `gg_set` and set your personal access token?

**Comment by alexreg** [comment]
> Did you do gg_set and set your personal access token?

Confirmed.

**Comment by danielecook** [comment]
@alexreg did you get it to work?

**Comment by GabLeRoux** [comment]
I confirm I also get this error on `0.5`

**Comment by danielecook** [comment]
Closing as I believe this issue is resolved.
